### ISSUE TITLE
[Extensions]Eversync is not working

### ISSUE THREAD

**Issue by DoveBoy** [kiwibrowser/android#62]
Eversync is not working, It's can't to sync bookmarks

**Comment by NotesOfReality** [comment]
Have you also tested Raindrop.io ?
I guess it could be useful to know if the issue is the Eversync extension itself or the bookmarks sync.

**Comment by zongou** [comment]
![Screenshot_2019-05-23-10-25-00-786_com kiwibrowser browser](https://user-images.githubusercontent.com/23202896/58221492-54dc1380-7cd8-11e9-9a54-dc4118817f89.png)
Raindrop.io doesn't work and it doesn't display the user interface correctly

**Comment by Dodgexander** [comment]
FYI I too have been seeking bookmark sync and eversync indeed does not work.. but it doesn't work on my windows computer with Firefox either.

raindrop.io does in fact work but you have to disable kiwi's add blocker for the UI to work. It redirects you to sign up in their website where again you have to disable the add blocker.

But it works @zongou @DoveBoy

**Comment by Dodgexander** [comment]
@KaKi87 this still isn't fixed. Eversync+xbookmarksync just don't sync bookmarks with Kiwi.

I think the issue may be down to the fact Kiwi restricts you to only 'Mobile Bookmarks' and doesn't let you import in any other folders.

**Comment by KaKi87** [comment]
You confirmed that another extension works.

**Comment by Dodgexander** [comment]
> You confirmed that another extension works.

The other extension (raindrop.io) does not sync the built in boomarks. It just keeps bookmarks in an entirely different place.

For me (and others I'm sure) one main thing stopping me from using Kiwi is lack of sync between desktop and mobile, so if these extensions could be made to work it would be brilliant.

With xbrowsersync the problem seems to be permissions related. It tries to request read/write permissions and force closes.

If there's any logs I can supply to help with the issue please let me know.

**Comment by KaKi87** [comment]
The official recommendation for syncing bookmarks between Kiwi and other browsers is [floccus](https://floccus.org/).

**Comment by Dodgexander** [comment]
> The official recommendation for syncing bookmarks between Kiwi and other browsers is [floccus](https://floccus.org/).

Thanks, good to know an alternative. Sadly it doesn't let me log in with my google drive. Hitting the button doesn't do anything.
