### ISSUE TITLE
Ad Blocker Breaks Site Functionality

### ISSUE THREAD

**Issue by pceiley** [kiwibrowser/android#9]
For example, the buttons don't work on this site unless the ad blocker is disabled:

https://www.dryjuly.com/beneficiaries/dryjulyfoundation/donations/new

**Comment by RuthlessRuler** [comment]
Yeah, It breaks many and thats due to the filterlist used by the adblocker have those types of elemtens to be blocked. It isnt possible to verify that a certain set set of rules will work with every website cause each website is designed diffrenetly and its impossible to make a list that will work fine with all of the websites on internet. So I highly recommend to see thoose ads or use uBlock + Firefox!

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
